[package]
name = "iui-builder"
version = "0.1.0"
authors = ["Tobia Conforto <tobia.conforto@gmail.com>"]
edition = "2018"

[dependencies]
iui = { git = "https://github.com/rust-native-ui/libui-rs.git" }
